# Numpy Tutorial

---

In [1]:
import numpy as np

In [2]:
#python list vs numpy array
py_list = [1, 2, 3,4,5]
np_arr = np.array([1, 2,3,4,5])


In [3]:
#operation on every element - no loop needed!
print(np_arr*2)
print(np_arr**2)
print(np_arr + 10)

[ 2  4  6  8 10]
[ 1  4  9 16 25]
[11 12 13 14 15]


In [4]:
#key attributes
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.size)
print(a.nbytes) #tells the no. byes used in memory

(2, 3)
2
int64
6
48


# Creating Arrays
---

### np.array() - convert any list/tuple to ndarray

In [9]:
#1D array
a = np.array([10,20,30])

#2D array
mat = np.array([[2,3,4],[5,6,7]])

#Force a specific dtype

f = np.array([1,2,3],dtype=np.float32)


### np.zeros/np.ones/np.full - Fill arrays

In [13]:
np.zeros((3,4)) # 3x4 matric of 0.0
np.ones((2,3)) # 2x4 matrix of 1.0
np.full((3,3),7) # 3x3 matrix filled with 7

#useful for initialising weights, bias, masks

weights = np.zeros((784,128)) #neural net layer init
bias = np.ones(128) #bias vector

### np.arange & np.linspace --Sequences

In [14]:
# arange : like range() but reuturns ndarray
np.arange(0,10,2) 
np.arange(5)
np.arange(1.0, 2.0 , 0.1) #works with floats too

#Linspace : N evenly - spaced points between start & stops

np.linspace(0, 1, 5) 
np.linspace(0,2*np.pi, 100)

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

### np.eye/np.identity/np.empty

In [22]:
np.eye(3) # 3x3 identity matrix
np.eye(3, k=1) # diagonal shifted by 1
np.empty((2,2)) # uninitialised(fast, use when you fill immediately)
np.empty_like(a) #same shape/dtype as array a
np.zeros_like (a) #same shape, all zeros
np.ones_like(a) #same shape, all ones

array([1, 1, 1])

#### arange vs linspace
- np.linspace is preferred over np.arange when you need a fixed number of points (e.g. plotting). Use
np.arange when you need a fixed step size.



---

# Indexing, Slicing & Reshaping
---

### 01-Basic Indexing & Slicing

In [25]:
a = np.array([10,20, 30 ,40, 50 ])
#indexing (0-based)
a[0] # 10 - first element
a[-1] # 50 - last element

#slicing [start:stop:step] [stop is exclusive]
a[1:4]
a[:3] # [10 20 30]
a[::2] # [10 30 50] — every 2nd element
a[::-1] # [50 40 30 20 10] — reverse
# 2D array indexing
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
m[1, 2] # 6 — row 1, col 2
m[0, :] # [1 2 3] — entire first row
m[:, 1] # [2 5 8] — entire second column


array([2, 5, 8])

### 02-Boolean Masking -- Filter data without loops

In [33]:
sales = np.array([120, 85,200,45,310,90,175])
#create a boolean mask
mask = sales>100
print(mask)
# Apply mask as filter
print(sales[mask])

# One-liner(most common in practice)
print(sales[sales>100]) # same result

# Combined Conditions
print(sales[(sales>100)&(sales <250)])

# Fancy indexing -- select specific indices
print(sales[[0,2,5]]) 



[ True False  True False  True False  True]
[120 200 310 175]
[120 200 310 175]
[120 200 175]
[120 200  90]


### 03-reshape, faltten, transpose -- Shape manipulation

In [40]:
a = np.arange(12)

#reshape -- change shape without changing data

b = a.reshape(3,4) # 3 rows, 4 cols
c = a.reshape(2,2,3) # 3d array -- 2 blocks of 2x3
print(c)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [55]:
d = a.reshape(-1, 4) # -1 = auto-calculate rows(=3)

# Flatten vs ravel

b.flatten() # returns copy - safe to modify
b.ravel() # returns view - faster, memory efficient

# Transpose
b.T # shape (3,4) -> (4,3)
np.transpose(b) # same as b.T

# Expand_dims & squeeze --add/removes dimensions

x = np.array([1,2,3]) # shape (3,)
print(x)
np.expand_dims(x, axis=0) # shape (1,3) -- add row dimensions
np.expand_dims(x, axis=1) # shape (3,1) -- add col dimensions
y = np.array([[[1,2,3]]]) # shape (1,2,3)
print(y)
print("y shape is : ")
y.shape
np.squeeze(y) # shape (3,) - remove size-1 dims

[1 2 3]
[[[1 2 3]]]
y shape is : 


array([1, 2, 3])

# Math & Element-wise Operations
---

### 01-Arithmetic & Comparison Operators

In [63]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])

# Element-wise arithmetic

a+b
b-a
a*b
b/a
a**b
b%a
b//3
a>2
a==b
a!=b

array([ True,  True,  True,  True])

### 03-Broadcasting -- Operate on different shapes
- Broadcasting allows NumPy to perform operations on arrays with different shapes by 'stretching' the smaller array.
This avoids writing explicit loops and is used constantly in ML.


In [68]:
# Scalar broadcast -- applies to every element
arr  = np.array([[1,2,3],[4,5,6]])
arr + 100 
arr*0.5

# 1D broadcast over 2D
row = np.array([10,20,30]) #shape(3,)
arr + row # adds [10,20,30] to EACH row of arr
# result: [[11 22 33],[14 25 36]]

# Column Broadcast
col = np.array([[100],[200]]) #shape(2,1]
arr + col

array([[101, 102, 103],
       [204, 205, 206]])

### 04-Universal Functions (ufuncs) & Utilities

In [79]:
x = np.array([-3.7, 0, 1.5, 4.2, 9.0])

# Math ufuncs
np.abs(x)
np.sqrt(np.abs(x))
np.exp(x)
np.log(np.abs(x)+1e-8)
np.round(x,1)
np.floor(x)
np.ceil(x)

# Trignometry
np.sin(x) ; np.cos(x); np.tan(x)

# np.clip -- bound values between min and max
np.clip(x, -2, 3)

# np.where - vectorised if-else (use CONSTANTLY)
labels = np.where(x>0, "positive", "non-positive")
values = np.where(x>0, x, 0) # Relu activation!

#np.sign
np.sign(x)

array([-1.,  0.,  1.,  1.,  1.])

- np.where(condition, x, y) is the vectorised version of Python's list comprehension [x if c else y for c in arr].
It's 10-50x faster and works on multi-dimensional arrays instantly.

# Aggreation & Statistics
---

### 01-Core Aggreation Functions

In [87]:
data = np.array([[4, 7, 2],
[1, 9, 5],
[8, 3, 6]])

# Over Entire Array
np.sum(data)
np.mean(data)
np.std(data)
np.var(data)
np.min(data)
np.max(data)
np.median(data)

# axis = 0 -> operate DOWN the rows (per column)

np.sum(data, axis = 0) # [13 19 13] — column sums
np.sum(data, axis = 1) # [13 15 17] — row sums

array([13, 15, 17])

- axis=0 sums → collapse rows, result has same cols
- axis=1 sums → collapse cols, result has same rows


### 02-Percentile, argmin, argmax -- Index-based stats

In [99]:
scores = np.array([88, 45, 92, 67, 78, 55, 99, 34])
np.percentile(scores, 75) # 75th percentile (Q3)
np.percentile(scores, [25,50,75]) # Q1, Q2, Q3 at once
np.argmin(scores) # 7 — INDEX of minimum value
np.argmax(scores) # 6 — INDEX of maximum value

# Cumulative operations
np.cumsum(scores) # running total
np.cumprod(np.array([1,2,3,4])) # [1 2 6 24]
np.diff(scores) # differences between consecutive elements

# Count items matching condition
np.sum(scores > 70) # 4 — count of passing scores
np.mean(scores > 70) # 0.5 — proportion passing (50%)

np.float64(0.5)

- The Proportion Trick   
np.mean(condition) gives you the proportion of True values — one line to compute accuracy, pass rate, or
prevalence. Memorise this trick.

# Array Manipulation
---

### 01-Concatenate, stack, vstack, hstack

In [112]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

#concatenate - join along existing axis
np.concatenate([a,b], axis=0)
np.concatenate([a,b], axis=1)

# shortcuts
np.vstack([a,b]) # same as axis=0 → (4,2)
np.hstack ([a,b]) # same as axis=1 → (2,4)

#stack - creates NEW axis
np.stack([a,b], axis=0) # shape (2,2,2) — new batch dimension

x = np.arange(12).reshape(6,2)

#split - divide into sub-arrays
parts = np.split(x, 3, axis=0) # 3 equal parts of shape (2,2)
np.array_split(x, 4) # allows unequal splits

[array([[0, 1],
        [2, 3]]),
 array([[4, 5],
        [6, 7]]),
 array([[8, 9]]),
 array([[10, 11]])]

### 02-sort, argsort, unique

In [120]:
socres = np.array([88, 45, 92, 67, 78])

#np.sort - returns sroted copy
np.sort(socres)
np.sort(scores)[::-1] #descending order

# np.argsort - returns INDICES that would sort array
idx = np.argsort(scores) # [1 3 4 0 2]
scores[idx] # [45 67 78 88 92] — same as sort

# Use argsort to get top-k predictions (ML)
probs = np.array([0.1, 0.6, 0.05, 0.25])
top2 = np.argsort(probs)[::-1][:2]# indices of top 2 probs

# np.unique - unique values + optimal counts
cats = np.array(["A","B","A","C","B","A"])
np.unique(cats)
vals, counts = np.unique(cats, return_counts=True)
print(dict(zip(vals,counts)))

{np.str_('A'): np.int64(3), np.str_('B'): np.int64(2), np.str_('C'): np.int64(1)}


### 03-NaN Handling - Critical for real datasets


In [125]:
data = np.array([1.0, 2.0, np.nan, 4.0, np.nan, 6.0])

# Detect NaN
np.isnan(data)
np.sum(np.isnan(data))

# NaN-safe aggregations (ignores NaN)
np.nanmean(data)
np.nansum(data)
np.nanstd(data)
np.nanmin(data)
np.nanmax(data)

# Replace NaN with mean(imputation)
data[np.isnan(data)] = np.nanmean(data)

# Linear Algebra -- p.linalg
---

### 01-dot, matmul(@) -- Matrix Multiplication

In [133]:
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[7,8,9],[10,11,12]])

# Matrix Multiplication - three equivalent ways
np.dot(A,B)
np.matmul(A,B)
A@B

# Dot Product of two 1D vectors
u = np.array([1,2,3])
v = np.array([4,5,6])
np.dot(u, v) # 32 = 1*4 + 2*5 + 3*6

# Outer Product
np.outer(u,v)

# Batch matrix mulptipy (3D arrays - used in deep learning)
X = np.random.randn(32,10,5) # batch of 32, each 10x5
W = np.random.randn(32, 5, 8)
X@Y

### 02-det, inv, solve, norm

In [137]:
from numpy import linalg as LA

M = np.array([[3.,1.],[1.,2.]])

# Determinant
LA.det(M) 

# Inverse (only for square non-sigular matrices)
LA.inv(M)

#solve system of equations Mx=b
b = np.array([9.,8.])
x = LA.solve(M,b)

print(x)

# Norm (vector/matrix magnitude)
v = np.array([3., 4.])
LA.norm(v) # 5.0 — L2 norm (Euclidean distance)
LA.norm(v, ord=1) # 7.0 — L1 norm (Manhattan)


[2. 3.]


np.float64(5.0)

### 03-eig, SVD - Dimensionality Reduction Foundation

In [144]:
# Eigenvalues & eigenvectors (PCA uses this)
eigenvalues, eigenvectors = LA.eig(M)
#print("Eigenvalues :", eigenvalues)

# Singular Value Decomposition (SVD)
# Used in PCA, recommender systems, image compression
X = np.random.randn(100, 10)
U, S, Vt = LA.svd(X, full_matrices = False)


# Keep top-k components (manual PCA)
k = 3
X_reduced = U[:,:k]@ np.diag(S[:k])

- Use LA.solve(A, b) instead of LA.inv(A) @ b. solve() is numerically more stable and significantly faster.


# Random Module -- np.random
---


### 01-seed, rand, randn -- Random number generation

In [145]:
 set seed for reproducibility
np.random.seed(42) # old API — still widely used
rng = np.random.default_rng(42) # new API (preferred)

# Uniform random floats [0, 1)
np.random.rand(3, 4) # shape (3,4)

# Standard normal (Gaussian): mean=0, std=1
np.random.randn(100) # 100 values from N(0,1)
np.random.randn(5, 3) # shape (5,3) — init neural net weights

# Random integers
np.random.randint(1, 7, size=10) # roll a die 10 times
np.random.randint(0, 100, (3,3)) # 3x3 matrix of ints

### 03-choice, shuffle, permutation

In [149]:
items = np.array(["A","B","C","D","E"])

# choice - random sampling
np.random.choice(items, size=3) # with replacement
np.random.choice(items, size=3, replace= False) # without replacement
np.random.choice(items, size=3, p=[0.5,0.2,0.1,0.1,0.1]) # weighted sampling

# shuffle — in-place random reorder
arr = np.arange(10)
np.random.shuffle(arr) # modifies arr in place
# permutation — returns new shuffled array (does NOT modify)
shuffled = np.random.permutation(arr) # safe copy
# Shuffle X and y together (train/test split pattern)
idx = np.random.permutation(len(arr))
X_shuffled = X[idx]
y_shuffled = y[idx]


array(['A', 'A', 'B'], dtype='<U1')

# Statistical Distributions
---

In [156]:
# Normal distribution : mean = mu, std = sigma
np.random.normal(loc=50, scale = 10, size=1000)

# Uniform : values between low and high
np.random.uniform(low = 0, high = 1, size = 2)

# Binomial : n trials, p probability
np.random.binomial(n=10, p=0.3, size =10)

# Poisson events with avg rate lambda
np.random.poisson(lam = 3, size=500)

# Exponential: time between events
np.random.exponential(scale = 2.0, size=300)

# Multinomial : useful for simulating category draws
np.random.multinomial(n=100, pvals=[0.3,0.5,0.2])

array([36, 49, 15], dtype=int32)

# NumPy for ML Workflows
---

### 01-Feature Scaling from Scratch

In [163]:
X = np.array([[100., 0.5, 3000.],
[200., 1.2, 5000.],
[150., 0.8, 4000.]])

# Min-Max Normalisation -> scales to [0,1]
X_min = X.min(axis=0)
X_max = X.max(axis=1)
X_norm =  (X-X_min)/(X_max-X_min)

# Standardisation (z-score) -> mean = 0, std = 1
X_mean = X.mean(axis=0)
X_std = X.std(axis=0)
X_scaled = (X- X_mean)/X_std

# IMPORTANT : compute stats on train, apply to test
train_mean = X_train.mean(axis=0)
train_std = X_train.std(axis=0)
X_test_scaled = (X_test - train_mean) / train_std # no leakag

### 02-One-Hot Encoding

In [164]:
# Convert integer Labels to one-hot vectors
labels = np.array([0, 2, 1, 0, 2]) # 3 classes
n_classes = 3
one_hot = np.eye(n_classes)[labels]
print(one_hot)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


### 03-Vectorised Cost Function (MSE)

In [167]:
# Mean Squared Error - without any python loop
y_true = np.array([3.0, 5.0, 2.5, 7.0, 4.0])
y_pred = np.array([2.8, 5.2, 2.1, 6.5, 4.3])

mse = np.mean((y_true - y_pred)**2)
rmse = np.sqrt(mse)
mae = np.mean(np.abs(y_true - y_pred))

# Binary Cross-Entropy (log loss)
y_true = np.array([1, 0, 1, 1, 0])
y_prob = np.array([0.9, 0.1, 0.8, 0.7, 0.3])

eps = 1e-8 # avoid log(0)
bce = -np.mean(y_true-np.log(y_prob+eps) + (1-y_true)*np.log(1-y_prob+eps))


### 04-Save & Load Arrays


In [172]:
# Save single array(binary, fast)
np.save("features.npy", X_scaled)
X_loaded = np.load("features.npy")

# Save multiple arrays
np.savez("dataset.npz", X=X_scaled, y = y_true)
data = np.load("dataset.npz")
X_back, y_back = data["X"], data["y"]

# Save as CSV (human readiable)
np.savetxt("data.csv", X_scaled, delimiter=",", header ="f1, f2,f3")
X_csv = np.loadtxt("data.csv", delimiter=",", skiprows = 1)
